### PR TITLE
Bug 1442

### PR DESCRIPTION
**Pull request by GuKKDevel**

### CODE REVIEW

**Comment by GuKKDevel** [comment]
Hi Brian,

I know this, but as there is the password for mysql-access needed it is includes/mysql.php.sample and has to be adjusted on the specific system.

As I don't know how to do this (until now) I assumed this to be done of one of the software-assessors.
I'm trying to connect to test3.cacert.org to have a look the respective file.

Greetings, Karl-Heinz

**Comment by GuKKDevel** [comment]
I think this can't and shouldn't be done.

To access mysql-databases you have for security to enter a username, a password and a database-name. if you give this information out of your control (like posting ithem in a public github-repository) you open the door for hackers or at least making it easier for them. 

Therefore only a mall number should know these information. 

Karl-Heinz

**Comment by bdmc** [comment]
On Thu, Nov 01, 2018 at 06:40:36PM +0000, Karl-Heinz G??dderz wrote:
> I think this can't and shouldn't be done.

I agree that it shouldn't be in a public place.  I was thinking of a
configuration file that was isolated from public view, rather than being
in source code.


Brian

**Comment by GuKKDevel** [comment]
the file includes/mysql.php.sample I mentioned is the really mysql.php-file. in the target-directory you change the three parameters user, password and database stored in the old file mysql.php and rename mysql.php.sample to mysql.php.

This procedure is very seldom necessary, because as you see, this connect-statement is the only real importent statement in the whole file. and therefor will seldom be changed.

But for information about what is done if you include mysql.php, it is necessary to know the structure.

Karl-Heinz

**Pull request merged**
