### PR TITLE
All mysql_-statments replaced by their corresponding mysqli_-statements

### PR DESCRIPTION
**Pull request by GuKKDevel**

### CODE REVIEW

**Comment by bdmc** [comment]
On Tue, Oct 30, 2018 at 10:06:50PM -0700, Karl-Heinz G??dderz wrote:
> 
> You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/CAcertOrg/cacert-devel/pull/7
> 
> -- Commit Summary --
> 
>   * All mysql_-statments replaced by their corresponding mysqli_-statements

Karl-Heinz,

From what I can see, there is a file missing from this, and so it can
not work.

includes/mysql.php is required for the system to work.


Brian

**Comment by GuKKDevel** [comment]
Hi Brian,

I closed this pull request and replaced it with pull request for bug-1442  
https://github.com/CAcertOrg/cacert-devel/pull/8

**Comment by bdmc** [comment]
On Thu, Nov 01, 2018 at 11:23:08AM +0100, Karl-Heinz G??dderz wrote:
> Hi Brian,
> 
> I know this, but as there is the password for mysql-access needed it is
> a sample and has to be adjusted on the specific system.

Ah, thank you.   I didn't know.

Going forward, we should move that password out of that file, probably.



Brian

**Comment by GuKKDevel** [comment]
I think this can't and shouldn't be done.

To access mysql-databases you have for security to enter a username, a password and a database-name. if you give this information out of your control (like posting ithem in a public github-repository) you open the door for hackers or at least making it easier for them. 

Therefore only a mall number should know these information. 

Karl-Heinz

**Comment by petermoo** [comment]
PHP has an .ini file read function. We could create a config file in the .ini format then read that into the code. There are also read functions for JSON and other formats that are a bit harder to create by hand.

**Comment by bdmc** [comment]
On Sat, Nov 03, 2018 at 09:17:10PM -0700, Peter wrote:
> PHP has an .ini file read function. We could create a config file in the .ini format then read that into the code. There are also read functions for JSON and other formats that are a bit harder to create by hand.

That was my thought too.

Put a file in /etc or someplace other than in the web tree, and it
should be safe, certainly from casual attack.



Brian

**Comment by bdmc** [comment]
On Sun, Nov 04, 2018 at 12:19:23AM -0400, Brian McCullough wrote:
> On Sat, Nov 03, 2018 at 09:17:10PM -0700, Peter wrote:
> > PHP has an .ini file read function. We could create a config file in the
> > .ini format then read that into the code. There are also read functions
> > for JSON and other formats that are a bit harder to create by hand.
> 
> That was my thought too.
> 
> Put a file in /etc or someplace other than in the web tree, and it
> should be safe, certainly from casual attack.

I suggest to use an ini-file which is easier to parse for humans and is more
natural to PHP.

Please be aware that the Perl based signer code (CommModule/client.pl) uses
the current includes/mysql.php and needs to be adapted to whatever
configuration mechanism will be used.


Kind regards
Jan

-- 
Jan Dittberner - CAcert Infrastructure Team Lead
Software Architect, Debian Developer
GPG-key: 4096R/0xA73E0055558FB8DD 2009-05-10
         B2FF 1D95 CE8F 7A22 DF4C  F09B A73E 0055 558F B8DD
https://jan.dittberner.info/

**Comment by bdmc** [comment]
It may be a silly couple of questions but...

1) What is the advantage of moving  to an .ini file and it there is an 
advantage, do the benefits justify the effort?

2) Moving the file - whatever format - to /etc may make it marginally 
more secure, but it still needs to be read by the webserver - so is 
potentially still accessible if the webserver gets hacked. These files 
generally contain an username and password for mysql and are often 
plaintext - if this is the case here,  would the effort be better spent 
in applying some form of encryption to the file's content.

In both cases, some form of cost-benefit analysis might be a good idea! 
There's a lot to be said for the adage "If it isn't broken, don't fix it!"


Regards

Alex


On 04/11/2018 09:16, Jan Dittberner wrote:
> On Sun, Nov 04, 2018 at 12:19:23AM -0400, Brian McCullough wrote:
>> On Sat, Nov 03, 2018 at 09:17:10PM -0700, Peter wrote:
>>> PHP has an .ini file read function. We could create a config file in the
>>> .ini format then read that into the code. There are also read functions
>>> for JSON and other formats that are a bit harder to create by hand.
>> That was my thought too.
>>
>> Put a file in /etc or someplace other than in the web tree, and it
>> should be safe, certainly from casual attack.
> I suggest to use an ini-file which is easier to parse for humans and is more
> natural to PHP.
>
> Please be aware that the Perl based signer code (CommModule/client.pl) uses
> the current includes/mysql.php and needs to be adapted to whatever
> configuration mechanism will be used.
>
>
> Kind regards
> Jan
>


---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Comment by petermoo** [comment]
If you choose encryption for the file needing the settings, you still need the previous steps of centralizing settings in an external file. To make the change easy to test and place in production, you can split the process into smaller steps. An external file would be one step.

Encryption has the problem of storing the access key and would be a separate issue that should not hold up any other code improvements.

**Pull request closed without merging**
