### PR TITLE
Download button on server certificate page

### PR DESCRIPTION
**Pull request by Valinwolf**
I mailed y'all requesting a download function and I was willing to help with it, being a web dev and all. I was pointed in the right direction, and now it is complete.
1. I have added a new file for the downloading the certificate (/pages/account/60.php)
2. Added a download button under the certificate displayed (/pages/account/15.php)

_**Note:** I have not tested it, beings I do not have a environment capable of testing it._

### CODE REVIEW

**Comment by BenBE** [comment]
Three comments on this patch:
1. First patch does not properly protect client from XSS via $REQUEST['certid'] inserted into the HTML
2. The GUI is not consistent with what already exists for client certificates (downloading of various formats via link)
3. Creating new files is discouraged, especially as this code should be kept similar to the one existing for client certificates.

Last but not least: Please note that there should exist a bug entry for the issue on bugs.cacert.org which is referenced in each commit as "bug ????: ". If you are missing an account there, drop me a mail and I'll push some buttons to convince our bug tracker to give you one.

**Comment by Valinwolf** [comment]
It does not have a bug because I did not know I was supposed to make one. I was talking with... \* pulls open web mail and proceeds to dig through the 483 emails *
Ah ha, here we are. Felix Dörre. I was talking with Felix. Here's the last email he sent me:

> Hi,
> 
> Aah ok, I see your issue. Yes, this could be useful.
> Currently, we're having internal problems that block/delay any changes to the software. We are working on getting those issues resolved, but that takes some time.
> Also we're having a "feature-stop", because we want to concentrate our efforts to getting the new software done and replace the current one completely as soon as possible.
> 
> Nevertheless, you could fork the repository (https://github.com/CAcertOrg/cacert-devel) and implement this issue on "release" to get this done. (Be warned, the code looks awful :-) )
> To help you getting started, you might look at "pages/account/6.php" that is the page that shows client certificates and afterwards at "pages/account/15.php" (and www/account.php).
> In order to maximize the chances of getting your patch into the software, you should try to touch as few code as possible, but as already said: non-essential changes to the current software are very hard to get through.
> 
> Kind regards,
> Felix

As for the XSS, I can fix that pretty easy. As for the GUI, it was just a quick-and-dirty thing. I can fix that too. As for the new file.... Hmm... I can find a different way...

**Comment by Valinwolf** [comment]
That _should_ work, but I do not know for sure. I'll double check the code while I wait.

**Comment by Ted-CAcert** [comment]
This request is too old now. There is no corresponding issue on the bugtracker which makes it impossible to judge this issue, especially since BenNE left CAcert quite some time ago. 

@Valinwolf, if you still want to have this pull request active please drop us a note. First information needed would be a description the problem which would be fixed by this request.

**Pull request closed without merging**
